export const routes = [
  {
    name: "Login",
    locale: "user.login",
    path: "/user/login",
    component: "User/Login",
    hideInMenu: true,
  },
  {
    path: "/dashboard",
    locale: "dashboard",
    name: "Dashboard",
    icon: "dashboard",
    exact: true,
    component: "pages/dashboard",
    routes: [
      {
        path: "/dashboard/analysis",
        locale: "dashboard.analysis",
        name: "analysis",
        component: "pages/dashboard/analysis",
        exact: true,
        accessTO: ["admin"],
      },
      {
        path: "/dashboard/monitor",
        locale: "dashboard.monitor",
        component: "pages/dashboard/monitor",
        name: "monitor",
        exact: true,
      },
      {
        path: "/dashboard/workbench",
        locale: "dashboard.workplace",
        component: "pages/dashboard/workbench",
        name: "workplace",
        exact: true,
      },
    ],
  },
  {
    path: "/projects",
    locale: "projects",
    name: "Projects",
    icon: "projects",
    redirect: "/projects/list",
    routes: [
      {
        path: "/projects/list",
        locale: "projects.list",
        name: "Project List",
        icon: "projects",
        exact: true,
        component: "pages/projects/list",
      },
      {
        path: "/projects/:id",
        locale: "projects.details",
        name: "Project Details",
        hideInMenu: true,
        icon: "projects",
        key: "projects",
        exact: true,
        component: "pages/projects/details",
      },
      {
        path: "/projects/:id/settings",
        locale: "projects.settings",
        icon: "settings",
        name: "Settings",
        parentKey: "details",
        exact: true,
        component: "pages/projects/settings",
      },
    ],
  },
  {
    path: "*",
    component: "404",
  },
];
